sudo: false
dist: trusty
language: c
env:
 - BASE=3.16 STATIC=shared
 - BASE=3.16 STATIC=shared EXTRA=CMD_CXXFLAGS=-std=c++11
 - BASE=3.16 STATIC=shared CMPLR=clang
 - BASE=3.16 STATIC=static
 - BASE=3.15 STATIC=shared
 - BASE=3.14 STATIC=shared
 - BASE=3.14 STATIC=static
 - BASE=R3.14.12.2 STATIC=shared TEST=NO
 - KSER=3.x KVER=3.2.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
 - KSER=3.x KVER=3.16.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
 - KSER=4.x KVER=4.9.1 EXTRA="-C mrmShared/linux KERNELDIR=$HOME/linux"
install:
 - ./.ci/prepare-epics.sh
 - ./.ci/prepare-linux.sh
script:
 - ./.ci/build-epics.sh
 - ./.ci/build-linux.sh
